project_id = "eaqowynwfoopypminhsy"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-session-reminders]
verify_jwt = false

[functions.auto-complete-bookings]
verify_jwt = false
